import type { Metadata } from 'next';
import { SourceBadge, SectionHeader } from '@egypt-one/ui';
import { Page } from '@/components/Container';
import { Boundary, RelatedLinks } from '@/components/Module';
import { encChapters } from '@/lib/encyclopedia';
import type { Locale } from '@egypt-one/i18n';

export const metadata: Metadata = {
  title: 'Visual encyclopedia of Egypt',
  description:
    'A visual encyclopedia of Egypt: traditional dress in all 27 governorates, the Egyptian table, flags and state symbols, epic battles, ancient provinces, crafts, the genetic map and Egyptian cinema.',
};

const heroChapter = encChapters[0]!;

export default async function EncyclopediaPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;

  return (
    <Page wide>
      <div className="surface relative mb-8 overflow-hidden p-0">
        <div className="relative h-[42vh] min-h-[300px] w-full">
          <img src={heroChapter.cover} alt="Traditional Egyptian dress of all 27 governorates" className="h-full w-full object-cover opacity-70" />
          <div className="absolute inset-0 bg-gradient-to-t from-void via-void/70 to-transparent" />
        </div>
        <div className="relative -mt-24 px-6 pb-9 sm:px-9">
          <div className="text-[11px] font-semibold uppercase tracking-[0.24em] text-gold-500">Visual encyclopedia</div>
          <h1 className="mt-2.5 max-w-3xl text-[30px] font-semibold leading-[1.12] sm:text-[40px]">
            Egypt through the ages — people, dress, food, symbols and science
          </h1>
          <p className="mt-3.5 max-w-2xl text-[14.5px] leading-relaxed text-ink-mid">
            Eight illustrated chapters that turn a national archive into something you can browse and plan a trip
            around. Every plate is a demonstration entry pending a licensed content partnership.
          </p>
          <div className="mt-6 flex flex-wrap gap-2">
            {encChapters.map((c) => (
              <a
                key={c.id}
                href={`#${c.id}`}
                className="rounded-full border border-white/12 bg-white/4 px-3 py-1.5 text-[12px] text-ink-mid backdrop-blur transition-colors hover:bg-white/8"
              >
                {c.eyebrow}
              </a>
            ))}
          </div>
        </div>
      </div>

      <div className="grid gap-16">
        {encChapters.map((chapter) => (
          <section key={chapter.id} id={chapter.id} className="scroll-mt-24">
            <SectionHeader eyebrow={chapter.eyebrow} title={chapter.title} sub={chapter.tagline} />
            <SourceBadge status="DEMO" className="mb-4" />

            <div className="grid gap-6 lg:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]">
              <p className="text-[14px] leading-relaxed text-ink-mid">{chapter.story}</p>
              <div className="grid content-start gap-3">
                {chapter.stats.map((s) => (
                  <div key={s.label} className="surface flex items-baseline justify-between gap-4 px-4 py-3">
                    <span className="text-[20px] font-semibold text-gold-300">{s.value}</span>
                    <span className="text-end text-[12px] text-ink-faint">{s.label}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="mt-8 grid gap-4 md:grid-cols-2">
              {chapter.plates.map((plate) => (
                <figure key={plate.caption} className={`surface overflow-hidden p-0 ${plate.wide ? 'md:col-span-2' : ''}`}>
                  <img src={plate.image} alt={plate.alt} loading="lazy" className="w-full object-cover" />
                  <figcaption className="border-t border-white/8 px-4 py-3">
                    <div className="text-[13.5px] font-semibold text-ink-hi">{plate.caption}</div>
                    <p className="mt-1 text-[12px] leading-relaxed text-ink-faint">{plate.note}</p>
                  </figcaption>
                </figure>
              ))}
            </div>
          </section>
        ))}
      </div>

      <div className="mt-12 grid gap-6">
        <Boundary
          points={[
            'Every chapter is editorial content ported from the design reference. None of it is generated by a live API — it will carry a source badge other than DEMO only once a licensed content or research partnership is signed.',
            'Historical dates and figures are presented for orientation and are not a substitute for an academic source.',
          ]}
        />
        <RelatedLinks
          locale={locale as Locale}
          links={[
            { href: '/heritage', label: 'Heritage registry', body: 'Every recorded site.' },
            { href: '/egypt-through-time', label: 'Egypt through time', body: 'The eras behind these chapters.' },
            { href: '/governorates', label: 'The 27 governorates', body: 'Where each dress family and craft lives.' },
            { href: '/research', label: 'Research & education', body: 'Academic partnerships, including the genome project.' },
          ]}
        />
      </div>
    </Page>
  );
}
